import 'dart:math';

class MyCnfHelper {
  double mbRam = 1024;
  double maxConnections = 200;

  getCnfText() {
    /**
     * https://www.saotn.org/mysql-innodb-performance-improvement/
     */

    //estimated value use 'show global status like '%Threads_connected%';'
    int threadConnected = 50;

    //number of tables, 50 is estimated
    int totalTables = 50;

    //https://galaxydata.ru/community/calculate-table_open_cache-mysql-1138
    double tableOpenCache = ((totalTables * threadConnected) * 0.5) * 2;

    //https://www.percona.com/blog/2007/09/17/mysql-what-read_buffer_size-value-is-optimal/
    double readBufferSize = 2;

    double readRndBufferSize = 2;

    double sortBufferSize = 1;

    double joinBufferSize = 1;

    //https://releem.com/docs/mysql-performance-tuning/thread_cache_size
    double threadCacheSize = 8 + (maxConnections / 100).floorToDouble();

    double queryCacheSize = max(mbRam / 8, 128);

    double innodbBufferPoolSize = mbRam * 0.65;

    //https://www.saotn.org/mysql-innodb-performance-improvement/
    double innodbBufferPoolInstances =
        (innodbBufferPoolSize / 1500).floorToDouble();

    double queryCacheLimit = 2;

    double tmpTableSize = 32;

    double keyBufferSize = mbRam * 0.8;

    return '''#BEGIN CONFIG INFO
#Generated by mysqlcnfbuilder.com
#Add/Update to [mysqld] section in my.cnf file

max_connections = ${maxConnections.toStringAsFixed(0)}
innodb_buffer_pool_size = ${innodbBufferPoolSize.toStringAsFixed(0)}M
innodb_buffer_pool_instances = ${innodbBufferPoolInstances.toStringAsFixed(0)}

; Number of I/O threads for writes
innodb_write_io_threads = 8
; Number of I/O threads for reads
innodb_read_io_threads = 8


table_open_cache = ${tableOpenCache.toStringAsFixed(0)}M
read_buffer_size = ${readBufferSize.toStringAsFixed(0)}M
read_rnd_buffer_size = ${readRndBufferSize.toStringAsFixed(0)}M
sort_buffer_size = ${sortBufferSize.toStringAsFixed(0)}M
join_buffer_size = ${joinBufferSize.toStringAsFixed(0)}M
thread_cache_size = ${threadCacheSize.toStringAsFixed(0)}M
query_cache_size = ${queryCacheSize.toStringAsFixed(0)}M
query_cache_limit = ${queryCacheLimit.toStringAsFixed(0)}M
tmp_table_size = ${tmpTableSize.toStringAsFixed(0)}M
key_buffer_size = ${keyBufferSize.toStringAsFixed(0)}M
''';
  }
}
